# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: prueba

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker --version'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker login -u iamapikey -p $(apikey) us.icr.io'
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: 'us.icr.io/azure-demo/java-test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'v1'
    
- stage: Deploy
#   variables:
#     environment: Dev
  dependsOn: Build
  jobs:
    - job: DevDeployJob
      steps:
      - bash: echo DeployJob
      - task: oc-setup@2
        inputs:
          connectionType: 'OpenShift Connection Service'
          openshiftService: 'roks-cluster'
          version: '4.6.23'
# A script task making use of 'oc'
      - script: |
          oc new-project $(project_name)
          oc get secret all-icr-io -n default -o yaml | sed 's/default/$(project_name)/g' | oc create -n $(project_name) -f -
          oc patch -n $(project_name) serviceaccount/default --type='json' -p='[{"op":"add","path":"/imagePullSecrets/-","value":{"name":"all-icr-io"}}]'
          oc apply -f $(System.DefaultWorkingDirectory)/openshift/deployment.yaml -n $(project_name)